version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
        prod-dependencies:
          dependency-type: production
        dev-dependencies:
          dependency-type: development
