[tool.poetry]
name = "sureflap_gcloud"
version = "0.1.0"
description = ""
authors = ["John Carter <john@therefromhere.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
astral = "^2.2"
pytz = "^2022.2.1"
surepy = "^0.9.0a"
asyncio = "^3.4.3"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
