[tool.poetry]
name = "sureflap_gcloud"
version = "0.1.0"
description = ""
authors = ["John Carter <john@therefromhere.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
astral = "^2.2"
pytz = "^2022.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
