#!/usr/bin/env bash

# Generate requirements.txt in the same format as pip-tools,
# from the current uv config

# adapted from https://github.com/win845/uv-light/blob/b4fabd9fc4fca621dd91bfe0a90e6ce6f17dd5ce/bin/uv-sync.sh

source ./scripts/_common_init.sh

PYTHON_VERSION=$(cat .python-version)

echo "Export uv.lock to requirements.txt"
uv export --no-hashes -o requirements.txt

# Add pip-compile like comment to the top of requirements.txt
# for dependabot to detect a pip-compile workflow
cat << EOF | cat - requirements.txt > temp && mv temp requirements.txt
#
# This file is autogenerated by pip-compile with Python $PYTHON_VERSION
# by the following command:
#
#    pip-compile pyproject.toml
#
#
# The above comment was added for dependabot to support uv.
#
EOF
