#!/usr/bin/env bash

# adapted from https://github.com/win845/uv-light/blob/b4fabd9fc4fca621dd91bfe0a90e6ce6f17dd5ce/bin/uv-sync.sh

set -e
set -u

PYTHON_VERSION=$(cat .python-version)
#BRANCH_NAME=${GITHUB_REF#refs/heads/}
AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
#AUTHOR_EMAIL=$(git log -1 --pretty=format:"%ae")

if [[ "$AUTHOR_NAME" == *dependabot* ]] ; then
    # Read requirements.txt, exclude comments, and format as TOML array
    constraints=$(grep -vE '^\s*#' requirements.txt | awk '{print "  \""$0"\","}')

    # Append constraint-dependencies to pyproject.toml
    cat <<EOF >> pyproject.toml

### generated scripts/uv-sync.sh , but not intended to be checked in! ###
constraint-dependencies = [
$constraints
]
EOF

    echo "Lock uv with a new requirements.txt as constraint"
    uv lock
fi

echo "Export uv.lock to requirements.txt"
uv export --no-hashes -o requirements.txt

# Add pip-compile like comment to the top of requirements.txt
# for dependabot to detect a pip-compile workflow
cat << EOF | cat - requirements.txt > temp && mv temp requirements.txt
#
# This file is autogenerated by pip-compile with Python $PYTHON_VERSION
# by the following command:
#
#    pip-compile pyproject.toml
#
#
# The above comment was added for dependabot to support uv.
#
EOF

#git add uv.lock requirements.txt
#if ! git diff --cached --quiet; then
#    git config --global user.name "$AUTHOR_NAME"
#    git config --global user.email "$AUTHOR_EMAIL"
#    git commit -m "Sync uv.lock and requirements.txt"
#    git push origin $BRANCH_NAME
#    echo "push changes"
#fi
