name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    concurrency: "prod"
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: Generate Requirements
        run: poetry export --output=requirements.txt
      - uses: mad9000/actions-find-and-replace-string@3
        name: Escape commas in ASTRAL_LOCATION
        id: astral_escaped
        with:
          source: ${{ vars.ASTRAL_LOCATION }}
          find: ','
          replaceAll: '\,'
      - name: debug env
        run:
          echo "ASTRAL_LOCATION_ESC=${{env.ASTRAL_LOCATION//,\\\,}}"
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{ vars.GCP_CLOUD_FUNCTION_NAME }}
          runtime: 'python311'
          entry_point: "update"
          env_vars: DEVICE_ID=${{ vars.DEVICE_ID }},ASTRAL_LOCATION=${{ steps.astral_escaped.outputs.value }},SUREPY_AUTH_TOKEN=${{ secrets.SUREPY_AUTH_TOKEN }}
