name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    concurrency: "prod"
    steps:
      - uses: 'actions/checkout@v4.2.2'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.1.7'
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version-file: "pyproject.toml"        
      - name: Install
        run: uv sync
      - name: Test
        run: uv run pytest -v
      - name: Generate Requirements
        run: uv export --output-file=requirements.txt
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3.0.7'
        with:
          name: "update2"
          runtime: 'python312'
          environment: GEN_2
          max_instance_count: 2
          entry_point: "update2"
          # TODO put these all in github or all in gcp
          environment_variables: |-
            DEVICE_ID=${{ vars.DEVICE_ID}}
          secrets: |-
            ASTRAL_LOCATION=projects/${{ steps.auth.outputs.project_id}}/secrets/ASTRAL_LOCATION/versions/latest
            SUREPY_AUTH_TOKEN=projects/${{ steps.auth.outputs.project_id}}/secrets/SUREPY_AUTH_TOKEN/versions/latest
      - name: Trigger deployed function
        run:
          curl ${{ steps.deploy.outputs.url }} --fail-with-body
